version: '3.0'
services:
  db:
    image: test-db
    environment:
       POSTGRES_PASSWORD: root
       POSTGRES_USER: postgres
       POSTGRES_DB: test-db
    expose:
      - "5432"
    ports:
      - 0.0.0.0:4432:5432/tcp
    build:
      context: ./
      dockerfile: ./psql_dockerFile
  ms:
    image: test-ms
    links:
       - db:db
    build:
      context: ./
      dockerfile: ./ms_dockerFile
    expose:
       - "8080"
    ports:
       - 0.0.0.0:8080:8080/tcp

